import assert from "node:assert/strict";

// Real editor commands only. DOM ranges simulate mouse selection, never mutations.
export async function exerciseAuthoring(page, origin) {
  const id = value => `[data-testid="${value}"]`;
  const editor = id("fixture-email");
  const source = () => page.$eval(id("fixture-email-source"), el => el.textContent);
  const click = value => page.click(id(value));
  const key = async key => {
    await page.keyboard.down("Control");
    await page.keyboard.press(key);
    await page.keyboard.up("Control");
  };
  const set = async (selector, value) => {
    await page.click(selector);
    await key("KeyA");
    await page.keyboard.sendCharacter(value);
  };
  const select = async (selector, collapse = false) => page.$eval(selector, (el, collapse) => {
    el.closest("[contenteditable]")?.focus();
    const range = document.createRange();
    range.selectNodeContents(el);
    if (collapse) range.collapse(false);
    const selection = window.getSelection();
    selection.removeAllRanges(); selection.addRange(range);
    el.dispatchEvent(new MouseEvent("mouseup", { bubbles: true }));
  }, collapse);
  await page.goto(`${origin}/editor-fixture`);
  await page.waitForSelector(editor);
  const mountedEditor = await page.$(editor);
  await page.click(editor);
  await page.keyboard.sendCharacter("Authored document A");
  const documentA = await source();
  await click("fixture-email-save");
  await click("fixture-email-load-other");
  assert.equal(await page.$eval(editor, el => el.textContent), "External document B");
  assert.equal(await page.$eval(id("fixture-email-undo"), el => el.disabled), true);
  await click("fixture-email-reopen");
  assert.equal(await mountedEditor.evaluate(el => el === document.querySelector('[data-testid="fixture-email"]')), true,
    "A/B/A must use the same mounted editor DOM, not a remount");
  assert.equal(await page.$eval(editor, el => el.textContent), "Authored document A");
  assert.equal(await source(), documentA);
  assert.equal(await page.$eval(id("fixture-email-undo"), el => el.disabled), true);
  assert.equal(await page.$eval(id("fixture-email-redo"), el => el.disabled), true);
  await select(editor, true);
  await page.keyboard.sendCharacter(" next edit");
  assert.equal(await page.$eval(editor, el => el.textContent), "Authored document A next edit");
  assert.match(await source(), /Authored document A next edit/);
  await click("fixture-email-undo");
  assert.equal(await source(), documentA);
  assert.equal(await page.$eval(editor, el => el.textContent), "Authored document A");
  assert.equal(await page.$eval(id("fixture-email-undo"), el => el.disabled), true,
    "Undo cannot return to B or to edits before the external replacement");
  console.log("PASS same-mounted external A/B/A hydration, next edit and reset history");
  await page.reload();
  await page.waitForSelector(editor);
  assert.equal(await page.$eval(id("fixture-email-undo"), el => el.disabled), true);
  assert.equal(await page.$eval(id("fixture-email-redo"), el => el.disabled), true);
  await page.click(editor);
  await page.keyboard.sendCharacter("History button check");
  const historyButtonValue = await source();
  assert.equal(await page.$eval(id("fixture-email-undo"), el => el.disabled), false);
  await click("fixture-email-undo");
  assert.equal(await source(), "");
  assert.equal(await page.$eval(id("fixture-email-undo"), el => el.disabled), true);
  assert.equal(await page.$eval(id("fixture-email-redo"), el => el.disabled), false);
  await click("fixture-email-redo");
  assert.equal(await source(), historyButtonValue);
  assert.equal(await page.$eval(id("fixture-email-redo"), el => el.disabled), true);
  await click("fixture-email-raw-mode");
  await click("fixture-email-undo");
  assert.equal(await page.$eval(id("fixture-email-raw"), el => el.value), "");
  await click("fixture-email-redo");
  assert.equal(await page.$eval(id("fixture-email-raw"), el => el.value), historyButtonValue);
  await click("fixture-email-raw-mode");
  await click("fixture-email-undo");
  console.log("PASS visible undo/redo buttons, boundary states and source-mode history");
  assert.equal(await page.$(id("fixture-email-page-break")), null, "Email has no physical page break control");
  await page.click(editor);
  await page.keyboard.type("Email heading");
  const typed = await source();
  await key("KeyZ");
  assert.notEqual(await source(), typed, "Typing participates in undo");
  await key("KeyY");
  assert.equal(await source(), typed, "Typing redo restores authored text");
  await select(editor);
  await click("fixture-email-bold");
  assert.match(await source(), /<(b|strong)[ >]|font-weight:bold/);
  await key("KeyZ");
  assert.equal(await source(), typed, "Formatting is one undoable command");
  await key("KeyY");
  await select(editor, true);
  const beforeToken = await source();
  await click("fixture-email-token");
  assert.match(await source(), /\{\{contact.field\(name="firstName"\)\}\}/);
  await key("KeyZ");
  assert.equal(await source(), beforeToken, "External token insertion is undoable");
  await key("KeyY");
  const beforePaste = await source();
  await page.$eval(editor, el => {
    const clipboardData = new DataTransfer();
    clipboardData.setData("text/html", '<table style="width:100%"><tbody><tr><td style="padding:8px">Outer<table><tbody><tr><td>Nested</td></tr></tbody></table></td><td>Right</td></tr></tbody></table>');
    el.dispatchEvent(new ClipboardEvent("paste", { bubbles: true, cancelable: true, clipboardData }));
  });
  assert.equal(await page.$$eval(`${editor} table`, els => els.length), 2);
  await key("KeyZ");
  assert.equal(await source(), beforePaste, "Nested layout paste is one undoable command");
  await key("KeyY");
  assert.equal(await page.$$eval(`${editor} table`, els => els.length), 2);
  await click("fixture-email-raw-mode");
  const tokenized = '<div style="color:#123456"><p>Quoted token layout</p><table style="width:100%"><tr><td><table><tr><td>Nested</td></tr></table></td><td><a href="{{contact.field(name="url")}}">Link</a><span style="color:{{contact.field(name="color")}}">{{contact.field(name="firstName")}}</span></td></tr></table></div>';
  await set(id("fixture-email-raw"), tokenized);
  await click("fixture-email-raw-mode");
  const canonical = await source();
  assert.match(canonical, /\{\{contact.field\(name="url"\)\}\}/);
  assert.match(canonical, /\{\{contact.field\(name="color"\)\}\}/);
  assert.doesNotMatch(canonical, /sirius\w+slot|siriustemplateplaceholder/);
  await click("fixture-email-save");
  await page.reload();
  await click("fixture-email-reopen");
  await page.waitForFunction(expected => document.querySelector('[data-testid="fixture-email-source"]').textContent === expected, {}, canonical);
  assert.equal(await page.$$eval(`${editor} table`, els => els.length), 2);
  await click("fixture-email-raw-mode");
  assert.equal(await page.$eval(id("fixture-email-raw"), el => el.value), canonical);
  await click("fixture-email-raw-mode");
  await click("fixture-email-disabled");
  assert.equal(await page.$eval(editor, el => el.isContentEditable), false);
  assert.equal(await page.$eval(id("fixture-email-undo"), el => el.disabled), true);
  assert.equal(await page.$eval(id("fixture-email-redo"), el => el.disabled), true);
  await click("fixture-email-token");
  assert.equal(await source(), canonical, "Disabled imperative insertion is refused");
  await click("fixture-email-disabled");
  const tools = `div:has(> ${editor})`;
  const control = label => `${tools} [aria-label="${label}"]`;
  const textClick = async (text, tag = "button") => {
    const handles = await page.$$(`${tools} ${tag}`);
    for (const handle of handles) {
      if ((await handle.evaluate(el => el.textContent.trim())) === text) {
        await handle.click(); return;
      }
    }
    throw new Error(`Missing ${tag}: ${text}`);
  };
  // Build a fresh email entirely through the visual controls.
  await click("fixture-email-raw-mode");
  await set(id("fixture-email-raw"), "<p>Designed email</p>");
  await click("fixture-email-raw-mode");
  await page.$eval(`${tools} summary[aria-label="Template design tools"]`, el => { if (!el.parentElement.open) el.click(); });
  await select(`${editor} p`);
  await page.select(control("Font"), "Georgia, serif");
  await page.select(control("Size"), "24px");
  await page.select(control("Align"), "center");
  await page.select(control("Line spacing"), "1.5");
  assert.match(await source(), /font-family:Georgia,serif/);
  assert.match(await source(), /font-size:24px/);
  assert.match(await source(), /text-align:center/);
  await select(`${editor} p`);
  await page.keyboard.down("Shift");
  await page.keyboard.press("F10");
  await page.keyboard.up("Shift");
  await page.waitForSelector('[role="menu"][aria-label="Editor selection actions"]');
  assert.match(await page.$eval('[role="menu"][aria-label="Editor selection actions"]', el => el.textContent), /Font….*Text color….*Highlight color…/s);
  await page.$eval('[role="menu"][aria-label="Editor selection actions"]', el => {
    [...el.querySelectorAll("button")].find(button => button.textContent.includes("Text color"))?.click();
  });
  const beforeColor = await source();
  await set(control("Text color hex"), "#12"); // incomplete RGB is only a draft
  assert.equal(await source(), beforeColor);
  await textClick("Cancel color changes");
  assert.equal(await source(), beforeColor);
  await set(control("Text color hex"), "#123456");
  assert.equal(await source(), beforeColor);
  await textClick("Apply text color");
  assert.match(await source(), /color:(?:#123456|rgb\(18,52,86\))/);
  await key("KeyZ");
  assert.equal(await source(), beforeColor);
  await select(`${editor} p`);
  await textClick("Text links", "summary");
  await set(control("Text link URL"), "https://example.invalid/help");
  await textClick("Add text link");
  assert.equal(await page.$eval(`${editor} a`, el => el.getAttribute("href")), "https://example.invalid/help");
  await select(`${editor} a`, true);
  await set(control("Text link URL"), "https://example.invalid/updated-help");
  await textClick("Update text link");
  assert.equal(await page.$eval(`${editor} a`, el => el.getAttribute("href")), "https://example.invalid/updated-help");
  await select(`${editor} a`, true);
  await textClick("Remove text link");
  assert.equal(await page.$(`${editor} a`), null);
  assert.match(await source(), /Designed email/);
  const beforeClear = await source();
  assert.match(beforeClear, /line-height:1.5/);
  await select(`${editor} p`);
  await textClick("Clear formatting");
  assert.doesNotMatch(await source(), /font-family:|font-size:|text-align:|line-height:/);
  assert.match(await source(), /Designed email/);
  await key("KeyZ");
  assert.equal(await source(), beforeClear, "Clear formatting is undoable");
  console.log("PASS ordinary text links add/update/remove and selection clear formatting/undo");
  await select(editor, true);
  await textClick("Tables", "summary");
  await set(control("Table rows"), "2");
  await set(control("Table columns"), "2");
  await textClick("Insert table");
  assert.equal(await page.$$eval(`${editor} td`, els => els.length), 4);
  await select(`${editor} td`, true);
  await textClick("Row below");
  assert.equal(await page.$$eval(`${editor} tr`, els => els.length), 3);
  await select(`${editor} td`, true);
  await textClick("Column right");
  assert.equal(await page.$$eval(`${editor} td`, els => els.length), 9);
  await select(`${editor} td`, true);
  await textClick("Merge right");
  assert.equal(await page.$eval(`${editor} td`, el => el.colSpan), 2);
  await select(`${editor} td`, true);
  await textClick("Split cell");
  assert.equal(await page.$$eval(`${editor} td`, els => els.length), 9);
  await select(`${editor} td`, true);
  await set(control("Table width"), "80");
  await set(control("Cell padding"), "16");
  await textClick("Apply table and cell properties");
  assert.equal(await page.$eval(`${editor} table`, el => el.style.width), "80%");
  assert.equal(await page.$eval(`${editor} td`, el => el.style.padding), "16px");
  await select(`${editor} td`, true);
  await textClick("Delete column");
  await select(`${editor} td`, true);
  await textClick("Delete row");
  assert.equal(await page.$$eval(`${editor} td`, els => els.length), 4);
  await select(editor, true);
  await textClick("Layouts and linked buttons", "summary");
  await textClick("2-column layout");
  assert.equal(await page.$$eval(`${editor} table`, els => els.length), 2);
  await select(editor, true);
  await set(control("Button text"), "View benefits");
  await set(control("Button link"), "https://example.invalid/benefits");
  await textClick("Insert linked button");
  assert.equal(await page.$eval(`${editor} a`, el => el.textContent), "View benefits");
  await select(editor, true);
  await textClick("Images", "summary");
  await set(control("Image URL"), "javascript:alert(1)");
  await textClick("Insert image");
  assert.equal(await page.$(`${editor} img`), null);
  assert.match(await page.$eval(tools, el => el.textContent), /HTTPS image URL/);
  await set(control("Image URL"), "https://fixture-images.invalid/logo.png");
  await set(control("Image alternative text"), "Benefits logo");
  await set(control("Image width"), "120");
  await textClick("Insert image");
  assert.equal(await page.$eval(`${editor} img`, el => el.alt), "Benefits logo");
  assert.equal(await page.$eval(`${editor} img`, el => el.style.height), "auto");
  await page.click(`${editor} img`);
  await page.keyboard.down("Shift"); await page.keyboard.press("ArrowRight"); await page.keyboard.up("Shift");
  assert.equal(await page.$eval(`${editor} img`, el => el.width), 130, "Keyboard resize preserves the image ratio");
  await key("KeyZ");
  assert.equal(await page.$eval(`${editor} img`, el => el.width), 120);
  await page.$eval(editor, el => {
    const image = el.querySelector("img");
    const target = el.querySelector("p");
    const point = target.getBoundingClientRect();
    const transfer = new DataTransfer();
    image.dispatchEvent(new DragEvent("dragstart", { bubbles: true, dataTransfer: transfer }));
    target.dispatchEvent(new DragEvent("drop", {
      bubbles: true, cancelable: true, dataTransfer: transfer,
      clientX: point.left + 8, clientY: point.top + 8,
    }));
  });
  assert.equal(await page.$eval(`${editor} img`, el => el.closest("p")?.textContent), "Designed email",
    "Dropping moves the image to a new insertion point in document flow");
  await key("KeyZ");
  assert.equal(await page.$eval(`${editor} img`, el => el.closest("p")), null);
  await page.click(`${editor} img`);
  await set(control("Image alternative text"), "Updated benefits logo");
  await textClick("Update image");
  assert.equal(await page.$eval(`${editor} img`, el => el.alt), "Updated benefits logo");
  const designed = await source();
  await click("fixture-email-save");
  await click("fixture-email-raw-mode");
  assert.equal(await page.$eval(id("fixture-email-raw"), el => el.value), designed);
  await click("fixture-email-raw-mode");
  await page.$eval(`${tools} summary[aria-label="Template design tools"]`, el => { if (!el.parentElement.open) el.click(); });
  await page.$$eval(`${tools} summary`, nodes => {
    const images = nodes.find(el => el.textContent.trim() === "Images");
    if (images && !images.parentElement.open) images.click();
  });
  await page.click(`${editor} img`);
  await textClick("Delete image");
  assert.equal(await page.$(`${editor} img`), null);
  await page.click(editor);
  await key("KeyZ");
  assert.equal(await page.$eval(`${editor} img`, el => el.alt), "Updated benefits logo");
  await page.screenshot({ path: "screenshots/template-design-authoring.png", fullPage: true });
  await page.reload();
  await click("fixture-email-reopen");
  await page.waitForFunction(expected => document.querySelector('[data-testid="fixture-email-source"]').textContent === expected, {}, designed);
  console.log("PASS visual typography, table rows/columns/merge/split/properties, columns, linked button, HTTPS image validation/edit/delete/undo and save/reopen");
  console.log("PASS email history: typing, formatting, token insertion, nested paste; quoted tokens source/save/reopen and disabled isolation");
}