// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/benefit-history/Current.tsx": () => import("../components/mockups/benefit-history/Current.tsx"),
  "./components/mockups/benefit-history/FilterableSpans.tsx": () => import("../components/mockups/benefit-history/FilterableSpans.tsx"),
  "./components/mockups/benefit-history/GroupedEras.tsx": () => import("../components/mockups/benefit-history/GroupedEras.tsx"),
  "./components/mockups/monthly-history/Current.tsx": () => import("../components/mockups/monthly-history/Current.tsx"),
  "./components/mockups/monthly-history/ExceptionAccordion.tsx": () => import("../components/mockups/monthly-history/ExceptionAccordion.tsx"),
  "./components/mockups/monthly-history/RunsAccordion.tsx": () => import("../components/mockups/monthly-history/RunsAccordion.tsx"),
  "./components/mockups/monthly-history/TimelineAccordion.tsx": () => import("../components/mockups/monthly-history/TimelineAccordion.tsx"),
  "./components/mockups/worker-coverage/CoverageFirst.tsx": () => import("../components/mockups/worker-coverage/CoverageFirst.tsx"),
  "./components/mockups/worker-coverage/Current.tsx": () => import("../components/mockups/worker-coverage/Current.tsx"),
  "./components/mockups/worker-coverage/CurrentRefined.tsx": () => import("../components/mockups/worker-coverage/CurrentRefined.tsx"),
  "./components/mockups/worker-coverage/MonthlyLedger.tsx": () => import("../components/mockups/worker-coverage/MonthlyLedger.tsx"),
  "./components/mockups/worker-coverage/RailLedger.tsx": () => import("../components/mockups/worker-coverage/RailLedger.tsx")
};
