// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/worker-coverage/CoverageFirst.tsx": () => import("../components/mockups/worker-coverage/CoverageFirst.tsx"),
  "./components/mockups/worker-coverage/Current.tsx": () => import("../components/mockups/worker-coverage/Current.tsx"),
  "./components/mockups/worker-coverage/MonthlyLedger.tsx": () => import("../components/mockups/worker-coverage/MonthlyLedger.tsx")
};
