#!/usr/bin/env npx tsx
/**
 * DEV-ONLY drizzle-kit wrapper.
 *
 * This script used to be the primary mechanism for syncing the dev DB to
 * `shared/schema*`. That role has been replaced by the per-component
 * migration framework (see `replit.md` → "Schema changes require migrations"
 * and `scripts/migrate/`). The startup drift gate now refuses to boot the
 * server if anything is out of sync.
 *
 * `db-push` is preserved ONLY for the developer-loop case of "I'm
 * iterating on a Drizzle schema locally and want to see drizzle-kit's
 * generated DDL before I hand-write a migration file." It is GATED behind
 * an explicit `ALLOW_DB_PUSH=1` environment variable so it cannot be run
 * accidentally and will not be invoked in production or by automation.
 *
 * Workflow:
 *   1. Edit `shared/schema*`.
 *   2. Run `ALLOW_DB_PUSH=1 npx tsx scripts/db-push.ts --dry-run` to see
 *      what drizzle-kit thinks the diff is.
 *   3. Author a migration file under `scripts/migrate/core/` or
 *      `scripts/migrate/components/<id>/`, register it, and run the
 *      server — the migration runner will apply it and the drift gate
 *      will pass.
 *
 * Do NOT use this script to apply schema changes to production. There is
 * no production code path that calls it.
 */
import { spawn } from "node:child_process";
import { writeFileSync, unlinkSync, existsSync } from "node:fs";
import { resolve } from "node:path";
import { Pool, neonConfig } from "@neondatabase/serverless";
import ws from "ws";
import * as fullSchema from "../shared/schema";
import { getSchemaManagingComponents } from "../shared/components";

neonConfig.webSocketConstructor = ws;

const RUNTIME_SCHEMA_FILE = resolve(process.cwd(), ".drizzle-runtime-schema.ts");
const RUNTIME_CONFIG_FILE = resolve(process.cwd(), ".drizzle-runtime.json");
const POSTGRES_TABLE_MISSING = "42P01";

interface PgError extends Error {
  code?: string;
}

async function getDisabledComponentTables(pool: Pool): Promise<string[]> {
  let componentMap: Record<string, boolean> = {};
  try {
    const result = await pool.query<{ value: unknown }>(
      `SELECT value FROM variables WHERE name = 'components' LIMIT 1`,
    );
    if (result.rows.length > 0) {
      const value = result.rows[0].value;
      if (value && typeof value === "object") {
        componentMap = value as Record<string, boolean>;
      }
    }
  } catch (err) {
    if ((err as PgError).code !== POSTGRES_TABLE_MISSING) throw err;
  }

  const disabledComponents = getSchemaManagingComponents().filter(c => {
    const enabled = componentMap[c.id] ?? c.enabledByDefault;
    return !enabled && c.schemaManifest;
  });
  if (disabledComponents.length === 0) return [];

  const allCandidates = disabledComponents.flatMap(
    c => c.schemaManifest!.tables,
  );
  const existing = await pool.query<{ table_name: string }>(
    `SELECT table_name FROM information_schema.tables
       WHERE table_schema = 'public' AND table_name = ANY($1)`,
    [allCandidates],
  );
  const existingSet = new Set(existing.rows.map(r => r.table_name));

  const disabled: string[] = [];
  for (const component of disabledComponents) {
    const tables = component.schemaManifest!.tables;
    const anyExists = tables.some(t => existingSet.has(t));
    if (!anyExists) disabled.push(...tables);
  }
  return disabled;
}

const DRIZZLE_NAME_SYMBOL_DESC = "drizzle:Name";

function getDrizzleTableName(value: unknown): string | null {
  if (!value || typeof value !== "object") return null;
  const sym = Object.getOwnPropertySymbols(value).find(
    (s) => s.description === DRIZZLE_NAME_SYMBOL_DESC,
  );
  if (!sym) return null;
  const name = (value as Record<symbol, unknown>)[sym];
  return typeof name === "string" ? name : null;
}

function buildEnabledExportList(disabledTables: Set<string>): {
  enabledNames: string[];
  excludedExportNames: string[];
} {
  const enabledNames: string[] = [];
  const excludedExportNames: string[] = [];
  for (const [exportName, value] of Object.entries(fullSchema)) {
    const tableName = getDrizzleTableName(value);
    if (tableName && disabledTables.has(tableName)) {
      excludedExportNames.push(exportName);
    } else {
      enabledNames.push(exportName);
    }
  }
  return { enabledNames, excludedExportNames };
}

function writeRuntimeSchema(enabledNames: string[]): void {
  const body =
    "// AUTO-GENERATED by scripts/db-push.ts. Do not edit or commit.\n" +
    "export {\n" +
    enabledNames.map((n) => `  ${n},`).join("\n") +
    "\n} from \"./shared/schema\";\n";
  writeFileSync(RUNTIME_SCHEMA_FILE, body);
  writeFileSync(
    RUNTIME_CONFIG_FILE,
    JSON.stringify({ schemaPath: "./.drizzle-runtime-schema.ts" }, null, 2),
  );
}

function cleanupRuntimeFiles(): void {
  for (const path of [RUNTIME_SCHEMA_FILE, RUNTIME_CONFIG_FILE]) {
    if (existsSync(path)) {
      try {
        unlinkSync(path);
      } catch {
        // best-effort cleanup
      }
    }
  }
}

function runDrizzleKit(extraArgs: string[]): Promise<number> {
  return new Promise((res, rej) => {
    const child = spawn("drizzle-kit", ["push", ...extraArgs], {
      stdio: "inherit",
      env: process.env,
    });
    child.on("error", rej);
    child.on("exit", (code) => res(code ?? 0));
  });
}

async function main() {
  if (process.env.ALLOW_DB_PUSH !== "1") {
    console.error(
      [
        "",
        "[db:push] REFUSED — db-push is a dev-only escape hatch.",
        "",
        "Schema changes are applied via the per-component migration framework now:",
        "  - Core schema changes:        scripts/migrate/core/",
        "  - Per-component changes:      scripts/migrate/components/<componentId>/",
        "  - Per-deployment baselines:   scripts/migrate/baseline/<replit>-<YYYYMMDD>.ts",
        "",
        "The server's startup drift check will refuse to boot if your DB is out",
        "of sync with the schema. Author a migration file instead of running push.",
        "",
        "If you really need to preview drizzle-kit's diff against your dev DB",
        "(e.g. to copy DDL into a migration you are writing), set ALLOW_DB_PUSH=1:",
        "    ALLOW_DB_PUSH=1 npx tsx scripts/db-push.ts --dry-run",
        "",
        "NEVER set ALLOW_DB_PUSH in production. See replit.md.",
        "",
      ].join("\n"),
    );
    process.exit(2);
  }

  const databaseUrl = process.env.NEON_DATABASE_URL ?? process.env.DATABASE_URL;
  if (!databaseUrl) {
    throw new Error("DATABASE_URL is not set");
  }

  cleanupRuntimeFiles();

  const extraArgs = process.argv.slice(2);
  const pool = new Pool({ connectionString: databaseUrl });

  let disabledTables: string[] = [];
  try {
    disabledTables = await getDisabledComponentTables(pool);
  } finally {
    await pool.end();
  }

  let exitCode = 0;
  try {
    if (disabledTables.length > 0) {
      const disabledSet = new Set(disabledTables);
      const { enabledNames, excludedExportNames } =
        buildEnabledExportList(disabledSet);
      writeRuntimeSchema(enabledNames);

      console.log(
        `[db:push] Skipping ${disabledTables.length} table(s) owned by disabled components:`,
      );
      console.log(`  ${disabledTables.join(", ")}`);
      if (excludedExportNames.length > 0) {
        console.log(
          `[db:push] Omitting ${excludedExportNames.length} schema export(s).`,
        );
      }
    }

    exitCode = await runDrizzleKit(extraArgs);
  } finally {
    cleanupRuntimeFiles();
  }
  process.exit(exitCode);
}

main().catch((err) => {
  cleanupRuntimeFiles();
  console.error(err);
  process.exit(1);
});
