#!/usr/bin/env npx tsx
import { spawn } from "node:child_process";
import { writeFileSync, unlinkSync, existsSync } from "node:fs";
import { resolve } from "node:path";
import { Pool, neonConfig } from "@neondatabase/serverless";
import ws from "ws";
import * as fullSchema from "../shared/schema";
import { getSchemaManagingComponents } from "../shared/components";

neonConfig.webSocketConstructor = ws;

const RUNTIME_SCHEMA_FILE = resolve(process.cwd(), ".drizzle-runtime-schema.ts");
const RUNTIME_CONFIG_FILE = resolve(process.cwd(), ".drizzle-runtime.json");
const POSTGRES_TABLE_MISSING = "42P01";

interface PgError extends Error {
  code?: string;
}

async function getDisabledComponentTables(pool: Pool): Promise<string[]> {
  let componentMap: Record<string, boolean> = {};
  try {
    const result = await pool.query<{ value: unknown }>(
      `SELECT value FROM variables WHERE name = 'components' LIMIT 1`,
    );
    if (result.rows.length > 0) {
      const value = result.rows[0].value;
      if (value && typeof value === "object") {
        componentMap = value as Record<string, boolean>;
      }
    }
  } catch (err) {
    if ((err as PgError).code !== POSTGRES_TABLE_MISSING) throw err;
  }

  const disabled: string[] = [];
  for (const component of getSchemaManagingComponents()) {
    const enabled = componentMap[component.id] ?? component.enabledByDefault;
    if (!enabled && component.schemaManifest) {
      disabled.push(...component.schemaManifest.tables);
    }
  }
  return disabled;
}

const DRIZZLE_NAME_SYMBOL_DESC = "drizzle:Name";

function getDrizzleTableName(value: unknown): string | null {
  if (!value || typeof value !== "object") return null;
  const sym = Object.getOwnPropertySymbols(value).find(
    (s) => s.description === DRIZZLE_NAME_SYMBOL_DESC,
  );
  if (!sym) return null;
  const name = (value as Record<symbol, unknown>)[sym];
  return typeof name === "string" ? name : null;
}

function buildEnabledExportList(disabledTables: Set<string>): {
  enabledNames: string[];
  excludedExportNames: string[];
} {
  const enabledNames: string[] = [];
  const excludedExportNames: string[] = [];
  for (const [exportName, value] of Object.entries(fullSchema)) {
    const tableName = getDrizzleTableName(value);
    if (tableName && disabledTables.has(tableName)) {
      excludedExportNames.push(exportName);
    } else {
      enabledNames.push(exportName);
    }
  }
  return { enabledNames, excludedExportNames };
}

function writeRuntimeSchema(enabledNames: string[]): void {
  const body =
    "// AUTO-GENERATED by scripts/db-push.ts. Do not edit or commit.\n" +
    "export {\n" +
    enabledNames.map((n) => `  ${n},`).join("\n") +
    "\n} from \"./shared/schema\";\n";
  writeFileSync(RUNTIME_SCHEMA_FILE, body);
  writeFileSync(
    RUNTIME_CONFIG_FILE,
    JSON.stringify({ schemaPath: "./.drizzle-runtime-schema.ts" }, null, 2),
  );
}

function cleanupRuntimeFiles(): void {
  for (const path of [RUNTIME_SCHEMA_FILE, RUNTIME_CONFIG_FILE]) {
    if (existsSync(path)) {
      try {
        unlinkSync(path);
      } catch {
        // best-effort cleanup
      }
    }
  }
}

function runDrizzleKit(extraArgs: string[]): Promise<number> {
  return new Promise((res, rej) => {
    const child = spawn("drizzle-kit", ["push", ...extraArgs], {
      stdio: "inherit",
      env: process.env,
    });
    child.on("error", rej);
    child.on("exit", (code) => res(code ?? 0));
  });
}

async function main() {
  if (!process.env.DATABASE_URL) {
    throw new Error("DATABASE_URL is not set");
  }

  // Defensive: clear any stale runtime files from a prior crashed run so
  // ad-hoc `npx drizzle-kit ...` invocations are never silently filtered.
  cleanupRuntimeFiles();

  const extraArgs = process.argv.slice(2);
  const pool = new Pool({ connectionString: process.env.DATABASE_URL });

  let disabledTables: string[] = [];
  try {
    disabledTables = await getDisabledComponentTables(pool);
  } finally {
    await pool.end();
  }

  let exitCode = 0;
  try {
    if (disabledTables.length > 0) {
      const disabledSet = new Set(disabledTables);
      const { enabledNames, excludedExportNames } =
        buildEnabledExportList(disabledSet);
      writeRuntimeSchema(enabledNames);

      console.log(
        `[db:push] Skipping ${disabledTables.length} table(s) owned by disabled components:`,
      );
      console.log(`  ${disabledTables.join(", ")}`);
      if (excludedExportNames.length > 0) {
        console.log(
          `[db:push] Omitting ${excludedExportNames.length} schema export(s).`,
        );
      }
    }

    exitCode = await runDrizzleKit(extraArgs);
  } finally {
    cleanupRuntimeFiles();
  }
  process.exit(exitCode);
}

main().catch((err) => {
  cleanupRuntimeFiles();
  console.error(err);
  process.exit(1);
});
