#!/usr/bin/env npx tsx
/**
 * Wrapper around `drizzle-kit push` that hides tables belonging to disabled
 * components (those with `managesSchema: true`) from the diff. Without this,
 * drizzle-kit would prompt to create or rename tables for components the site
 * has intentionally turned off (e.g. BTU on a non-BTU deployment), because
 * `shared/schema.ts` re-exports every component's tables unconditionally.
 *
 * Strategy:
 *   1. Read the `components` variable from the database (the same map
 *      `server/services/component-cache.ts` writes) and decide which
 *      schema-managing components are disabled.
 *   2. Load `shared/schema` to determine which JS export names correspond to
 *      tables owned by those disabled components (matched via the SQL table
 *      names in each component's `schemaManifest.tables`).
 *   3. Generate `.drizzle-runtime-schema.ts` that re-exports every enabled
 *      runtime value from `./shared/schema` while omitting the disabled-table
 *      exports. Companion `.drizzle-runtime.json` tells `drizzle.config.ts`
 *      to point drizzle-kit at the generated file.
 *   4. Spawn `drizzle-kit push`, forwarding any extra CLI args (e.g.
 *      `--force`, `--verbose`).
 *   5. Always delete the generated files afterwards so re-runs start clean and
 *      the regular `npx drizzle-kit ...` commands still work against the full
 *      schema.
 *
 * Talks to the DB directly (via `@neondatabase/serverless`) instead of going
 * through the storage layer so it can run without booting the full server.
 */
import { spawn } from "node:child_process";
import { writeFileSync, unlinkSync, existsSync } from "node:fs";
import { resolve } from "node:path";
import { Pool, neonConfig } from "@neondatabase/serverless";
import ws from "ws";
import * as fullSchema from "../shared/schema";
import { getSchemaManagingComponents } from "../shared/components";

neonConfig.webSocketConstructor = ws;

const RUNTIME_SCHEMA_FILE = resolve(process.cwd(), ".drizzle-runtime-schema.ts");
const RUNTIME_CONFIG_FILE = resolve(process.cwd(), ".drizzle-runtime.json");

async function getDisabledComponentTables(pool: Pool): Promise<string[]> {
  let componentMap: Record<string, boolean> = {};
  try {
    const result = await pool.query(
      `SELECT value FROM variables WHERE name = 'components' LIMIT 1`
    );
    if (result.rows.length > 0) {
      const value = result.rows[0].value;
      if (value && typeof value === "object") {
        componentMap = value as Record<string, boolean>;
      }
    }
  } catch (err: any) {
    // If `variables` itself doesn't exist yet (fresh DB) we cannot tell which
    // components are enabled, so fall back to enabledByDefault for all.
    if (err?.code !== "42P01") throw err;
  }

  const disabled: string[] = [];
  for (const component of getSchemaManagingComponents()) {
    const enabled = componentMap[component.id] ?? component.enabledByDefault;
    if (!enabled && component.schemaManifest) {
      disabled.push(...component.schemaManifest.tables);
    }
  }
  return disabled;
}

function buildEnabledExportList(disabledTables: Set<string>): {
  enabledNames: string[];
  excludedExportNames: string[];
} {
  const enabledNames: string[] = [];
  const excludedExportNames: string[] = [];
  for (const [exportName, value] of Object.entries(fullSchema)) {
    if (value && typeof value === "object") {
      const nameSymbol = Object.getOwnPropertySymbols(value).find(
        (s) => s.description === "drizzle:Name"
      );
      if (nameSymbol) {
        const sqlName = (value as any)[nameSymbol];
        if (typeof sqlName === "string" && disabledTables.has(sqlName)) {
          excludedExportNames.push(exportName);
          continue;
        }
      }
    }
    enabledNames.push(exportName);
  }
  return { enabledNames, excludedExportNames };
}

function writeRuntimeSchema(enabledNames: string[]): void {
  const body =
    "// AUTO-GENERATED by scripts/db-push.ts. Do not edit or commit.\n" +
    "// Re-exports only enabled-component tables from shared/schema for db:push.\n" +
    "export {\n" +
    enabledNames.map((n) => `  ${n},`).join("\n") +
    "\n} from \"./shared/schema\";\n";
  writeFileSync(RUNTIME_SCHEMA_FILE, body);
  writeFileSync(
    RUNTIME_CONFIG_FILE,
    JSON.stringify({ schemaPath: "./.drizzle-runtime-schema.ts" }, null, 2)
  );
}

function cleanupRuntimeFiles(): void {
  for (const path of [RUNTIME_SCHEMA_FILE, RUNTIME_CONFIG_FILE]) {
    if (existsSync(path)) {
      try {
        unlinkSync(path);
      } catch {
        // best-effort cleanup
      }
    }
  }
}

function runDrizzleKit(extraArgs: string[]): Promise<number> {
  return new Promise((res, rej) => {
    const child = spawn("drizzle-kit", ["push", ...extraArgs], {
      stdio: "inherit",
      env: process.env,
    });
    child.on("error", rej);
    child.on("exit", (code) => res(code ?? 0));
  });
}

async function main() {
  if (!process.env.DATABASE_URL) {
    throw new Error("DATABASE_URL is not set");
  }

  const extraArgs = process.argv.slice(2);
  const pool = new Pool({ connectionString: process.env.DATABASE_URL });

  let disabledTables: string[] = [];
  try {
    disabledTables = await getDisabledComponentTables(pool);
  } finally {
    await pool.end();
  }

  let exitCode = 0;
  try {
    if (disabledTables.length > 0) {
      const disabledSet = new Set(disabledTables);
      const { enabledNames, excludedExportNames } =
        buildEnabledExportList(disabledSet);
      writeRuntimeSchema(enabledNames);

      console.log(
        `[db:push] Skipping ${disabledTables.length} table(s) owned by disabled components:`
      );
      console.log(`  ${disabledTables.join(", ")}`);
      if (excludedExportNames.length > 0) {
        console.log(
          `[db:push] Omitting ${excludedExportNames.length} schema export(s): ${excludedExportNames.join(", ")}`
        );
      }
    }

    exitCode = await runDrizzleKit(extraArgs);
  } finally {
    cleanupRuntimeFiles();
  }
  process.exit(exitCode);
}

main().catch((err) => {
  cleanupRuntimeFiles();
  console.error(err);
  process.exit(1);
});
